# MT940 file ingestion configuration
mt940:
  base-dir: mt940/
  inbox-dir: mt940/inbox/
  processing-dir: mt940/processing/
  archive-dir: mt940/archive/
  quarantine-dir: mt940/quarantine/

# VAN file ingestion configuration
van:
  base-dir: van/
  inbox-dir: van/inbox/
  processing-dir: van/processing/
  archive-dir: van/archive/
  quarantine-dir: van/quarantine/
# Common configuration for all environments
spring:
  application:
    name: payment-reconciliation
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
        default_schema: payment_flow

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    "[com.example.paymentreconciliation]": INFO

file:
  upload:
    base-dir: uploads/

# JWT Configuration
app:
  jwt:
    secret: ${APP_JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    issuer: ${APP_JWT_ISSUER:user-auth-service}
    audience: ${APP_JWT_AUDIENCE:payment-services}
    expiration: ${APP_JWT_EXPIRATION:86400}
  swagger:
    title: "Payment Reconciliation Service API"

# Auditing toggle
auditing:
  enabled: true

shared-lib:
  security:
    enabled: true
    permitted-paths:
      - /actuator/**
      - /v3/api-docs/**
      - /swagger-ui/**
      - /swagger-ui.html
    introspection:
      url: ${AUTH_SERVICE_BASE_URL:http://auth-service:8080}/internal/auth/introspect
      api-key: ${INTERNAL_API_KEY:}
      api-key-header: X-Internal-Api-Key
